---
# key-value mapping of actor-leak site URL
sites:
  54bb47h: http://54bb47h5qu4k7l4d7v5ix3i6ak6elysn3net4by4ihmvrhu7cvbskoqd.onion/blog.ws
  0mega: http://omegalock5zxwbhswbisc42o2q2i54vdulyvtqqbudqousisjgc7j7yd.onion.ws/
  0mega: https://0mega.cc/
  againstthewest: http://giphvoitymatg4cv7bxqh5dz6sn6bfscywoat4qtslztkomf5lavrayd.onion.ws/
  ako: http://giphvoitymatg4cv7bxqh5dz6sn6bfscywoat4qtslztkomf5lavrayd.onion.ws/
  alphv: http://2cuqgeerjdba2rhdiviezodpu3lc4qz2sjf4qin6f7std2evleqlzjid.onion.ws/
  alphv: http://alphvmmm27o3abo3r2mlmjrpdmzle3rykajqc5xsj7j7ejksbpsa36ad.onion.ws/
  alphv: http://vqifktlreqpudvulhbzmc5gocbeawl67uvs2pttswemdorbnhaddohyd.onion.ws/
  arvin: http://xxz6hl6wwoa25er62tbjdxda4nxyt5iqziavb73mhda6q6zujsgfoxqd.onion.ws/
  astrostream: http://anewset3pcya3xvk73hj7yunuamutxxsm5sohkdi32blhmql55tvgqad.onion.ws/
  atomsilo: http://mhdehvkomeabau7gsetnsrhkfign4jgnx3wajth5yb5h6kvzbd72wlqd.onion.ws/
  atomsilo: http://l5cjga2ksw6rxumu5l4xxn3cmahhi2irkbwg3amx6ajroyfmfgpfllid.onion.ws/
  avaddon: http://avaddongun7rngel.onion.ws/
  avoslocker: http://avosqxh72b5ia23dl5fgwcpndkctuzqvh2iefk5imp3pi5gfhel5klad.onion.ws/
  avoslocker: http://avos2fuj6olp6x36.onion.ws/
  babuk: http://wavbeudogz6byhnardd2lkp2jafims3j7tj6k6qnywchn2csngvtffqd.onion.ws/
  babuk: http://nq4zyac4ukl4tykmidbzgdlvaboqeqsemkp4t35bzvjeve6zm2lqcjid.onion.ws/
  babyduck: http://babydovegkmhbontykziyq7qivwzy33mu4ukqefe4mqpiiwd3wibnjqd.onion.ws/
  bianlian: http://bianlianlbc5an4kgnay3opdemgcryg2kpfcbgczopmm3dnbz3uaunad.onion/.ws
  bitlocker: http://mmeeiix2ejdwkmseycljetmpiwebdvgjts75c63camjofn2cjdoulzqd.onion.ws/
  blackbasta: https://stniiomyjliimcgkvdszvgen3eaaoz55hreqqx6o77yvmpwt7gklffqd.onion.ws/
  blackbyte: http://ce6roic2ykdjunyzazsxmjpz5wsar4pflpoqzntyww5c2eskcp7dq4yd.onion.ws/
  blackbyte: http://6iaj3efye3q62xjgfxyegrufhewxew7yt4scxjd45tlfafyja6q4ctqd.onion.ws/
  blackbyte: http://f5uzduboq4fa2xkjloprmctk7ve3dm46ff7aniis66cbekakvksxgeqd.onion.ws/
  blackbyte: http://dlyo7r3n4qy5fzv4645nddjwarj7wjdd6wzckomcyc7akskkxp4glcad.onion.ws/
  blackbyte: http://fl3xpz5bmgzxy4fmebhgsbycgnz24uosp3u4g33oiln627qq3gyw37ad.onion.ws/
  blackmatter: http://blackmax7su6mbwtcyo3xwtpfxpm356jjqrs34y4crcytpw7mifuedyd.onion.ws/
  blackmatter: http://supp24maprinktc7uizgfyqhisx7lkszb6ogh6lwdzpac23w3mh4tvyd.onion/EWX33VYY3IGOXSG5ZZ2.ws
  blackshadow: https://blackshadow.cc/
  blackshadow: http://544corkfh5hwhtn4.onion.ws/
  bluesky: http://ccpyeuptrlatb2piua4ukhnhi7lrxgerrcrj4p2b5uhbzqm2xgdjaqid.onion.ws/
  bonacigroup: http://bonacifryrxr4siz6ptvokuihdzmjzpveruklxumflz5thmkgauty2qd.onion.ws/
  CHEERS: http://rwiajgajdr4kzlnrj5zwebbukpcbrjhupjmk6gufxv6tg7myx34iocad.onion.ws/
  CLOP: http://santat7kpllt6iyvqbr7q4amdv6dzrh6paatvyrzl7ry3zm72zigf4ad.onion.ws/
  CLOP: http://ekbgzchl6x2ias37.onion.ws/
  conti: http://continewsnv5otx5kaoje7krkto2qbu3gtqef22mnr7eaxw3y6ncz3ad.onion.ws/
  conti: https://continews.click/
  coomingproject: http://teo7aj5mfgzxyeme.onion.ws/
  coomingproject: http://z6mikrtphid5fmn52nbcbg25tj57sowlm3oc25g563yvsfmygkcxqbyd.onion.ws/
  coomingproject: http://coomingproject.com/
  crimsonwalrus: http://ncpbxzcgdeprrbba7dgodmymdewy57yokkebuwhmuywiuz5kqjwepbad.onion.ws/
  ccrylock: http://d57uremugxjrafyg.onion.ws/
  cryp70n1c0d3: http://7k4yyskpz3rxq5nyokf6ztbpywzbjtdfanweup3skctcxopmt7tq7eid.onion.ws/
  cuba: http://cuba4mp6ximo2zlo.onion.ws/
  cuba: http://cuba4ikm4jakjgmkezytyawtdgr2xymvy6nvzgw5cglswg3si76icnqd.onion.ws/
  darkangels: https://wemo2ysyeq6km2nqhcrz63dkdhez3j25yw2nvn7xba2z4h7v7gyrfgid.onion.ws/
  darkside: http://darksidc3iux462n6yunevoag52ntvwp6wulaz3zirkmh4cnz6hhj7id.onion.ws/
  dopple: http://hpoo4dosa3x4ognfxpqcrjwnsigvslm7kv6hvmhh2yqczaxy3j6qnwad.onion.ws/
  dotadmin: http://adminavf4cikzbv6mbbp7ujpwhygnn2t3egiz2pswldj32krrml42wyd.onion.ws/
  ECH0RAIX: http://veqlxhq7ub5qze3qy56zx2cig2e6tzsgxdspkubwbayqije6oatma6id.onion.ws/
  entropy: http://leaksv7sroztl377bbohzl42i3ddlfsxopcb6355zc7olzigedm5agad.onion.ws/
  ep918: http://dg5fyig37abmivryrxlordrczn6d6r5wzcfe2msuo5mbbu2exnu46fid.onion.ws/
  everest: http://ransomocmou6mnbquqz44ewosbkjk3o5qjsl3orawojexfook2j7esad.onion.ly.ws/
  evilcorp: http://hpoo4dosa3x4ognfxpqcrjwnsigvslm7kv6hvmhh2yqczaxy3j6qnwad.onion.ws/
  exorcist: http://7iulpt5i6whht6zo2r52f7vptxtjxs3vfcdxxazllikrtqpupn4epnqd.onion.ws/
  freecivilian: http://gcbejm2rcjftouqbxuhimj5oroouqcuxb2my4raxqa7efkz5bd5464id.onion.ws/
  goodwill: http://9855-13-235-50-147.ngrok.io/
  grreif: http://griefcameifmv4hfr3auozmovz5yi6m3h3dwbuqw7baomfxoxz4qteid.onion.ws/
  groove: http://ws3dh6av66sjbxxkjpw5ao3wqzmtejnkzheswm4dz5rrwvular7xvkqd.onion.ws/
  hades: http://ixltdyumdlthrtgx.onion.ws/
  haron: http://ft4zr2jzlqoyob7yg4fcpwyt37hox3ajajqnfkdvbfrkjioyunmqnpad.onion/blog.php.ws
  hellokitty: http://3r6n77mpe737w4sbxxxrpc5phbluv6xhtdl5ujpnlvmck5tc7blq2rqd.onion.ws/
  hive: http://hiveleakdbtnp76ulyhi52eag6c6tyc3xw7ez7iqy6wc34gd2nekazyd.onion.ws/
  hive: http://hivecust6vhekztbqgdnkks64ucehqacge3dij3gyrrpdp57zoq3ooqd.onion.ws/
  holyghost: http://matmq3z3hiovia3voe2tix2x54sghc3tszj74xgdy4tqtypoycszqzqd.onion.ws/
  hotarus: http://r6d636w47ncnaukrpvlhmtdbvbeltc6enfcuuow3jclpmyga7cz374qd.onion.ws/
  katakurt: https://lhxxtrqraokn63f3nubhbjrzxkrgduq3qogp3yr424tkpvh3z7n4kcyd.onion.ws/
  karakurt: https://omx5iqrdbsoitf3q4xexrqw5r5tfw7vp3vl3li3lfo7saabxazshnead.onion.ws/
  karakurt: https://3f7nxkjway3d223j27lyad7v5cgmyaifesycvmwq7i7cbs23lb6llryd.onion.ws/
  karma: http://3nvzqyo6l4wkrzumzu5aod7zbosq4ipgf7ifgj3hsvbcr5vcasordvqd.onion.ws/
  lilith: http://yeuajcizwytgmrntijhxphs6wn5txp2prs6rpndafbsapek3zd4ubcid.onion.ws/
  lockbit: http://lockbitapt2yfbt7lchxejug47kmqvqqxvvjpqkmevv4l3azl3gy6pyd.onion.ws/
  lockbit: http://lockbitapt6vx57t3eeqjofwgcglmutr3a35nygvokja5uuccip4ykyd.onion.ws/
  lockbit: http://lockbitapt34kvrip6xojylohhxrwsvpzdffgs5z4pbbsywnzsbdguqd.onion.ws/
  lockbit: http://lockbitaptc2iq4atewz2ise62q63wfktyrl4qtwuk5qax262kgtzjqd.onion.ws/
  lockbit: http://lockbitaptq7ephv2oigdncfhtwhpqgwmqojnxqdyhprxxfpcllqdxad.onion.ws/
  lockbit: http://lockbitaptstzf3er2lz6ku3xuifafq2yh5lmiqj5ncur6rtlmkteiqd.onion.ws/
  lockbit: http://oyarbnujct53bizjguvolxou3rmuda2vr72osyexngbdkhqebwrzsnad.onion.ws/
  lockbit: http://www.lockbitapt.uz/
  lockbit: http://lockbitapt2d73krlbewgv27tquljgxr33xbwwsp6rkyieto7u4ncead.onion.ws/
  lockbit: http://lockbitapt2yfbt7lchxejug47kmqvqqxvvjpqkmevv4l3azl3gy6pyd.onion.ws/
  lockbit: http://lockbitapt34kvrip6xojylohhxrwsvpzdffgs5z4pbbsywnzsbdguqd.onion.ws/
  lockbit: http://lockbitapt5x4zkjbcqmz6frdhecqqgadevyiwqxukksspnlidyvd7qd.onion.ws/
  lockbit: http://lockbitapt6vx57t3eeqjofwgcglmutr3a35nygvokja5uuccip4ykyd.onion.ws/
  lockbit: http://lockbitapt72iw55njgnqpymggskg5yp75ry7rirtdg4m7i42artsbqd.onion.ws/
  lockbit: http://lockbitaptawjl6udhpd323uehekiyatj6ftcxmkwe5sezs4fqgpjpid.onion.ws/
  lockbit: http://lockbitaptbdiajqtplcrigzgdjprwugkkut63nbvy2d5r4w2agyekqd.onion.ws/
  lockbit: http://lockbitaptc2iq4atewz2ise62q63wfktyrl4qtwuk5qax262kgtzjqd.onion.ws/
  lockbit: http://lockbit7z2jwcskxpbokpemdxmltipntwlkmidcll2qirbu7ykg46eyd.onion.ws/
  lockbit: http://lockbitkodidilol.onion.ws/
  lockfile: http://zqaflhty5hyziovsxgqvj2mrz5e5rs6oqxzb54zolccfnvtn5w2johad.onion.ws/
  lorenz: http://lorenzmlwpzgxq736jzseuterytjueszsvznuibanxomlpkyxk6ksoyd.onion.ws/
  lv: http://rbvuetuneohce3ouxjlbxtimyyxokb4btncxjbo44fbgxqy7tskinwad.onion.ws/
  lv: http://4qbxi3i2oqmyzxsjg4fwe4aly3xkped52gq5orp6efpkeskvchqe27id.onion.ws/
  marketo: https://marketo.cloud/
  marketo: http://g5sbltooh2okkcb2.onion.ws/
  marketo: http://jvdamsif53dqjycuozlaye2s47p7xij4x6hzwzwhzrqmv36gkyzohhqd.onion.ws/
  marketo: http://fvki3hj7uxuirxpeop6chgqoczanmebutznt2mkzy6waov6w456vjuid.onion.ws/
  mbc: http://xembshruusobgbvxg4tcjs3jpdnks6xrr6nbokfxadcnlc53yxir22ad.onion.ws/
  medusalocker: http://qd7pcafncosqfqu3ha6fcx4h6sr7tzwagzpcdcnytiw3b6varaeqv5yd.onion.ws/
  midas: http://midasbkic5eyfox4dhnijkzc7v7e4hpmsb2qgux7diqbpna4up4rtdad.onion/blog.php.ws
  mindware: http://dfpc7yvle5kxmgg6sbcp5ytggy3oeob676bjgwcwhyr2pwcrmbvoilqd.onion.ws/
  mosesstaff: http://moses-staff.se/
  mosesstaff: http://mosesstaffm7hptp.onion.ws/
  mount: http://mountnewsokhwilx.onion.ws/
  mydecryptor: http://58b87e60649ccc808ac8mstiejnj.5s4ixqul2enwxrqv.onion.ws/
  n3tworm: http://n3twormruynhn3oetmxvasum2miix2jgg56xskdoyihra4wthvlgyeyd.onion.ws/
  nefilim: http://hxt254aygrsziejn.onion.ws/
  nemty: http://nemty.top/
  nemty: http://zjoxyw5mkacojk5ptn2iprkivg5clow72mjkyk5ttubzxprjjnwapkad.onion.ws/
  netwalker: http://rnfdsgm6wb6j6su5txkekw4u4y47kp2eatvu7d6xhyn5cs4lt4pdrqqd.onion.ws/
  nightsky: http://gg5ryfgogainisskdvh4y373ap3b2mxafcibeh2lvq5x7fx76ygcosad.onion.ws/
  nokoyawa: http://lirncvjfmdhv6samxvvlohfqx7jklfxoxj7xn3fh7qeabs3taemdsdqd.onion.ws/
  onepercent: http://5mvifa3xq5m7sou3xzaajfz7h6eserp5fnkwotohns5pgbb5oxty3zad.onion.ws/
  onyx: http://mrdxtxy6vqeqbmb4rvbvueh2kukb3e3mhu3wdothqn7242gztxyzycid.onion.ws/
  pandora: http://vbfqeh5nugm6r2u2qvghsdxm3fotf5wbxb5ltv6vw77vus5frdpuaiid.onion.ws/
  pay2key: http://pay2key2zkg7arp3kv3cuugdaqwuesifnbofun4j6yjdw5ry7zw2asid.onion.ws/
  payload: http://vbmisqjshn4yblehk2vbnil53tlqklxsdaztgphcilto3vdj4geao5qd.onion.ws/
  prolock: http://msaoyrayohnp32tcgwcanhjouetb5k54aekgnwg7dcvtgtecpumrxpqd.onion.ws/
  prometheus: http://promethw27cbrcot.onion/blog.ws
  pysa: http://pysa2bitc5ldeyfak4seeruqymqs4sj5wt5qkcq7aoyg4h2acqieywad.onion/partners.html.ws
  qlocker: http://gvka2m4qt5fod2fltkjmdk4gxh5oxemhpgmnmtjptms6fkgfzdd62tad.onion.ws/
  quantum: http://quantum445bh3gzuyilxdzs5xdepf3b7lkcupswvkryf3n7hgzpxebid.onion.ws/
  quantum: http://quantumleap.quest/
  quantum: http://mtr.ddns.mobi/
  ragnar: http://p6o7m73ujalhgkiv.onion.ws/
  ragnar: http://rgleaktxuey67yrgspmhvtnrqtgogur35lwdrup4d3igtbm3pupc4lyd.onion.ws/
  ragnar: http://ragnarleaks.top/
  ragnarok: http://sushlnty2j7qdzy64qnvyb6ajkwg7resd3p6agc2widnawodtcedgjid.onion.ws/
  ragnarok: http://wobpitin77vdsdiswr43duntv6eqw4rvphedutpaxycjdie6gg3binad.onion.ws/
  ransomcartel: http://u67aylig7i6l657wxmp274eoilaowhp3boljowa6bli63rxyzfzsbtyd.onion.ws/
  ransomexx: http://rnsm777cdsjrsdlbs4v5qoeppu3px6sb2igmh53jzrx7ipcrbjz5b2ad.onion.ws/
  ransomhouse: http://xw7au5pnwtl6lozbsudkmyd32n6gnqdngitjdppybudan3x3pjgpmpid.onion.ws/
  ranzy: http://37rckgo66iydpvgpwve7b2el5q2zhjw4tv4lmyewufnpx4lhkekxkoqd.onion.ws/
  redalert: http://blog2hkbm6gogpv2b3uytzi3bj5d5zmc4asbybumjkhuqhas355janyd.onion.ws/
  revil: http://blogxxu75w63ujqarv476otld7cyjkq4yoswzt4ijadkjwvg3vrvd5yd.onion/Blog.ws
  revil: http://landxxeaf2hoyl2jvcwuazypt6imcsbmhb7kx3x33yhparvtmkatpaad.onion.ws/
  revil: http://dnpscnbaix6nkwvystl3yxglz7nteicqrou3t75tpcc5532cztc46qyd.onion.ws/
  rook: http://gamol6n6p2p4c3ad7gxmx3ur7wwdwlywebo2azv3vv5qlmjmole2zbyd.onion.ws/
  rransom: http://t2tqvp4pctcr7vxhgz5yd5x4ino5tw7jzs3whbntxirhp32djhi7q3id.onion/check_payment_form.ws
  snatch: https://snatch.press/
  snatch: http://snatch.vip/
  snatch: http://hl66646wtlp2naoqnhattngigjp5palgqmbwixepcjyq5i534acgqyad.onion/index.php.ws
  sodinokibi: http://dnpscnbaix6nkwvystl3yxglz7nteicqrou3t75tpcc5532cztc46qyd.onion.ws/
  spookdata: http://spookuhvfyxzph54ikjfwf2mwmxt572krpom7reyayrmxbkizbvkpaid.onion/blog.ws
  stormous: http://3slz4povugieoi3tw7sblxoowxhbzxeju427cffsst5fo2tizepwatid.onion.ws/
  sugar: http://chat5sqrnzqewampznybomgn4hf2m53tybkarxk4sfaktwt7oqpkcvyd.onion/gate.php?data=.ws
  sugar: https://sugarpanel.space/advauth_ffma
  suncrypt: http://nbzzb6sa6xuura2z.onion.ws/
  suncrypt: http://x2miyuiwpib2imjr5ykyjngdu7v6vprkkhjltrk4qafymtawey4qzwid.onion.ws/
  synack: http://xqkz2rmrqkeqf6sjbrb47jfwnqxcd4o2zvaxxzrpbh2piknms37rw2ad.onion.ws/
  vfokx: http://vfokxcdzjbpehgit223vzdzwte47l3zcqtafj34qrr26htjo4uf3obid.onion.ws/
  vfokx: http://746pbrxl7acvrlhzshosye3b3udk4plurpxt2pp27pojfhkkaooqiiqd.onion.ws/
  vicesociety: http://4hzyuotli6maqa4u.onion.ws/
  vicesociety: http://vsociethok6sbprvevl4dlwbqrzyhxcxaqpvcqt5belwvsuxaxsutyad.onion.ws/
  vicesociety: http://ecdmr42a34qovoph557zotkfvth4fsz56twvwgiylstjup4r5bpc4oad.onion.ws/
  X001XS: http://nalr2uqsave7y2r235am5jsfiklfjh5h4jc5nztu3rzvmhklwt5j6kid.onion.ws/
  xing: http://xingnewj6m4qytljhfwemngm7r7rogrindbq7wrfeepejgxc3bwci7qd.onion.ws/
  xinof: http://wj3b2wtj7u2bzup75tzhnso56bin6bnvsxcbwbfcuvzpc4vcixbywlid.onion.ws/
  YANLUOWANG: http://jukswsxbh3jsxuddvidrjdvwuohtsy4kxg2axbppiyclomt2qciyfoad.onion.ws/
  zeon: http://zeonrefpbompx6rwdqa5hxgtp2cxgfmoymlli3azoanisze33pp3x3yd.onion.ws/
  elcometa: http://something.onion
  lockdata: http://something.onion
  # this has to be their API url, see readme for details
  hive: http://hiveleakdbtnp76ulyhi52eag6c6tyc3xw7ez7iqy6wc34gd2nekazyd.onion.ws/
  hive: http://hivecust6vhekztbqgdnkks64ucehqacge3dij3gyrrpdp57zoq3ooqd.onion.ws/
  rook: http://gamol6n6p2p4c3ad7gxmx3ur7wwdwlywebo2azv3vv5qlmjmole2zbyd.onion.ws/

# slack webhooks
notifications:
  dest1:
    # type of notification
    # valid options: slack, discord, Teams
    type: slack

    # url for the webhook (slack, discord, Teams)
    url: https://hooks.slack.com/services/something/goes/here

    # should new victim notifications be sent to this webhook?
    new_victims: true

    # should removed victim notifications be sent to this webhook?
    removed_victims: true

    # should notifications be sent to this webhook if a site is detected as down?
    down_sites: true

    # should errors be sent to this webook?
    errors: true

    # may in the future add support for not sending leak site links
    # if you actively want this, open an issue (or make a PR)
  dest2:
    type: slack
    url: https://hooks.slack.com/services/something/else/goes/here
    new_victims: true
    removed_victims: true
    down_sites: true
    errors: false

    # disord webhooks
notifications:
  dest1:
    # type of notification
    # valid options: slack, discord, Teams
    type: discord

    # url for the webhook (slack, discord, Teams)
    url: https://discordapp.com/api/webhooks/997196963772641430/PUoTQjWNNA82e_FJooi0fYdLOtrr4nzyhGkN1Gt8CajIZCAOxzwbRc8vF4jBA95x7doT

    # should new victim notifications be sent to this webhook?
    new_victims: true

    # should removed victim notifications be sent to this webhook?
    removed_victims: true

    # should notifications be sent to this webhook if a site is detected as down?
    down_sites: true

    # should errors be sent to this webook?
    errors: true

    # may in the future add support for not sending leak site links
    # if you actively want this, open an issue (or make a PR)
  dest2:
    type: dsicord
    url: https://discordapp.com/api/webhooks/997196963772641430/PUoTQjWNNA82e_FJooi0fYdLOtrr4nzyhGkN1Gt8CajIZCAOxzwbRc8vF4jBA95x7doT
    new_victims: true
    removed_victims: true
    down_sites: true
    errors: false

# how many seconds to wait for a connection
# this is used to check if the site is up, and doesn't wait
# for the full page data to be downloaded
timeout: 30

# tor proxy settings
# the values set below are for the provided docker-compose.yml
# adjust for your own custom environment
proxy:
  # hostname for the proxy
  hostname: proxy

  # port for the SOCKS proxy
  socks_port: 9050

  # port for the tor control service
  control_port: 9051

  # password for the tor control service
  password: password
